# Node.js
# Build a general Node.js project with npm. (backend)
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

jobs:
- job: buildandtest
  pool:
    vmImage: ubuntu-latest
  steps:
  - script: |
      npm install
    workingDirectory: '$(Build.SourcesDirectory)'
    displayName: 'install app'
  - task: CopyFiles@2
    inputs:
      Contents: 'dist/**'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'
  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(Build.ArtifactStagingDirectory)/dist'
      includeRootFolder: false
      archiveType: zip
      archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
      replaceExistingArchive: true
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
  - task: AzureWebApp@1
    inputs:
      azureSubscription: 'Azure subscription 1(8fe3a8ef-f474-4bc2-a35d-158de982642a)'
      appType: 'webAppLinux'
      appName: 'aibiz-web'
      deployToSlotOrASE: true
      resourceGroupName: 'AibizGrupo'
      slotName: 'production'
      package: '$(Build.ArtifactStagingDirectory)/**/*.zip'
      runtimeStack: 'NODE|18-lts'