###
POST  http://localhost:5000/api/v1/empresas
content-type: application/json

{
  "subDominio":"monasterio", 
  "nombreEmpresa":"monasterio", 
  "rif":"J-111111-1",
  "email":"ricardosequeira4@gmail.com"
}
###
POST  http://localhost:5000/api/v1/auth/login
content-type: application/json

{
  "email":"ricardosequeira4@gmail.com", 
  "password":"6ebd3415703f05fa2a43"
}

###
POST  http://localhost:5000/api/v1/auth/logout
content-type: application/json
###
POST  http://localhost:5000/api/v1/rols
content-type: application/json