###
POST  http://localhost:5000/v1/empresas
content-type: application/json

{
  "subDominio":"monasterio", 
  "nombreEmpresa":"monasterio", 
  "rif":"J-111111-1",
  "email":"ricardosequeira4@gmail.com"
}
###
POST  http://localhost:5000/v1/auth/login
content-type: application/json

{
  "email":"ricardosequeira4@gmail.com", 
  "password":"6ebd3415703f05fa2a43"
}

###
POST  http://localhost:5000/v1/users/create/programador
content-type: application/json

{
  "nombre": "Ricardo Sequeira",
  "email":"ricardosequeira4@gmail.com", 
  "password":"ricardo1",
  "telefono":"04246870359"
}